name="aodi-website"
main = "dist/index.cjs"
compatibility_date = "2026-02-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./apps/web/.next/standalone/apps/web/public"

[vars]
NODE_ENV = "production"

[build]
upload_include = ["seed/data/*.json"]